language: node_js
node_js:
- '4.0'
- '5.0'
- '6.0'
sudo: false
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: KIOBGKFkJNVKaAs+f7ZrjmfQLFc1/we1Ss2lm5RzyeFbxfuIdO5jTtAB7KQeaEnry/ye9C4IklGdnwN35TZuG0qCRVBGNddV/gtB3FcfD9GxEi8MWiroC4A5F2Uv112P25GM6L8YG2vZBdAGrjOGVCEiN0OixCJVBzvjOfCOSzI=
    on:
      tags: true
      node: '5.0'
  - provider: releases
    api_key:
      secure: T1HM8rpCijuQ+y4ee37t3pgsufm3DIot71Ejf2n2wSKyp8PukcOflV71XOt2Sw+7DvZ2lCsL5qTwIHf7NVlXJlBse1Fd69nNTc1U2AZztVZI7gxL1kHCOwZFDJEUtJYPqwHAe8uPtDoaHBQ6u0cPysQmmDraIZMfwy40wNnOOVY=
    file:
      - "markdown-table.js"
      - "markdown-table.min.js"
    on:
      tags: true
      node: '6.0'
